# Generated by Django 3.0.8 on 2020-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0002_auto_20200725_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='username',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
