# Generated by Django 3.0.8 on 2020-07-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0005_auto_20200728_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletteruser',
            name='users',
        ),
    ]
