# Generated by Django 3.0.8 on 2020-07-28 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsLetterApp', '0006_remove_newsletteruser_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='newsletters_included',
        ),
        migrations.AddField(
            model_name='newsletteruser',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
