# Generated by Django 3.0.8 on 2020-07-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0008_auto_20200728_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
