# Generated by Django 3.0.8 on 2020-08-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0012_newsletter_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='cat_date_added',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
