# Generated by Django 3.0.8 on 2020-08-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0014_delete_newsletteruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='cat_name',
            new_name='name',
        ),
    ]
