# Generated by Django 3.0.8 on 2020-08-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0015_auto_20200803_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
