# Generated by Django 3.0.8 on 2020-08-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0016_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='category',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='category',
            field=models.ManyToManyField(to='newsLetterApp.Tag'),
        ),
    ]
