# Generated by Django 3.0.8 on 2020-08-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0018_auto_20200803_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='bulletins',
        ),
    ]
