# Generated by Django 3.0.8 on 2020-08-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0019_auto_20200803_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='bulletins',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(to='newsLetterApp.Tag'),
        ),
    ]
