# Generated by Django 3.0.8 on 2020-08-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0025_auto_20200803_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='author',
        ),
    ]
