# Generated by Django 3.0.8 on 2020-08-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0028_newsletter_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagsNewsletter',
        ),
    ]
