# Generated by Django 3.0.8 on 2020-08-04 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0029_delete_tagsnewsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsLetterApp.Newsletter')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsLetterApp.Tag')),
            ],
        ),
    ]
