# Generated by Django 3.0.8 on 2020-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0032_newsletter_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='tags',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(to='newsLetterApp.Tag'),
        ),
    ]
