# Generated by Django 3.0.8 on 2020-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0033_auto_20200804_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsnewsletter',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagsnewsletter',
            name='tags',
            field=models.ManyToManyField(to='newsLetterApp.Tag'),
        ),
    ]
