# Generated by Django 3.0.8 on 2020-08-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0034_auto_20200804_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='tags',
        ),
    ]
