# Generated by Django 3.0.8 on 2020-08-04 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsLetterApp', '0035_remove_newsletter_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsnewsletter',
            name='newsletters',
        ),
        migrations.AddField(
            model_name='tagsnewsletter',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagsnewsletter',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tagsnewsletter',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tagsnewsletter',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
