# Generated by Django 2.2.14 on 2020-08-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsLetterApp', '0039_auto_20200816_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
