# Generated by Django 2.2.14 on 2020-08-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
